package com.example.kca_student_app;

import androidx.appcompat.app.AppCompatActivity;

import android.app.Dialog;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.RatingBar;
import android.widget.TextView;

import com.example.kca_student_app.ui.rate.RateUsFragment;

public class RateUsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.rate_us_activity);

        // add rating dialogue

        Button rankBtn = (Button) findViewById(R.id.rank_button);
        rankBtn.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
              final   Dialog rankDialog = new Dialog(RateUsActivity.this, R.style.FullHeightDialog);
                rankDialog.setContentView(R.layout.rank_dialog);
                rankDialog.setCancelable(true);
               final RatingBar ratingBar = (RatingBar) rankDialog.findViewById(R.id.dialog_ratingbar);
                float userRankValue = 0;
                ratingBar.setRating(userRankValue);

                TextView text = (TextView) rankDialog.findViewById(R.id.rank_dialog_text1);
                String name = null;
                text.setText(name);

                Button updateButton = (Button) rankDialog.findViewById(R.id.rank_dialog_button);
                updateButton.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        rankDialog.dismiss();
                    }
                });
                //now that the dialog is set up, it's time to show it
                rankDialog.show();
            }
        });

        // code below was generated by Android Studio
        if (savedInstanceState == null) {
            getSupportFragmentManager().beginTransaction()
                    .replace(R.id.container, RateUsFragment.newInstance())
                    .commitNow();
        }
    }
}